version: "3.8"

services:

  # RADARR - MOVIE DOWNLOAD AND MANAGEMENT
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    networks:
      - arr-net
    mem_limit: 512m
    memswap_limit: 512m
    volumes:
      - ${DOCKER_BASE_FOLDER}/radarr:/config
      - ${MEDIA_DISK_LOCATION}/movies:/movies
      - ${MEDIA_DISK_LOCATION}/downloads:/downloads
      - ${DOCKER_BASE_FOLDER}/shared:/shared
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 7878:7878
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${MY_TMZ}
    labels:
      - "com.containrrr.watchtower=true"

  # SONARR - TV SHOW DOWNLOAD AND MANAGEMENT
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    networks:
      - arr-net
    mem_limit: 512m
    memswap_limit: 512m
    volumes:
      - ${DOCKER_BASE_FOLDER}/sonarr:/config
      - ${MEDIA_DISK_LOCATION}/shows:/shows
      - ${MEDIA_DISK_LOCATION}/downloads:/downloads
      - ${DOCKER_BASE_FOLDER}/shared:/shared
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8989:8989
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${MY_TMZ}
    labels:
      - "com.containrrr.watchtower=true"

  # LIDARR - MUSIC DOWNLOADS
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    hostname: lidarr
    networks:
      - arr-net
    mem_limit: 512m
    memswap_limit: 512m
    volumes:
      - ${DOCKER_BASE_FOLDER}/lidarr/config:/config
      - ${MEDIA_DISK_LOCATION}/music:/music
      - ${MEDIA_DISK_LOCATION}/downloads:/downloads
      - ${DOCKER_BASE_FOLDER}/shared:/shared
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8686:8686
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${MY_TMZ}
    labels:
      - "com.containrrr.watchtower=true"

  # PROWLARR - INDEXER MANAGEMENT
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    networks:
      - arr-net
    mem_limit: 256m
    memswap_limit: 256m
    volumes:
      - ${DOCKER_BASE_FOLDER}/prowlarr:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9696:9696
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${MY_TMZ}
    labels:
      - "com.containrrr.watchtower=true"

  # SABNZBD - USENET DOWNLOADER
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    hostname: sabnzbd
    networks:
      - arr-net
    mem_limit: 1g
    memswap_limit: 1g
    volumes:
      - ${DOCKER_BASE_FOLDER}/sabnzbd:/config
      - ${MEDIA_DISK_LOCATION}/downloads:/downloads
      - ${DOCKER_BASE_FOLDER}/shared:/shared
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${MY_TMZ}
    labels:
      - "com.containrrr.watchtower=true"

  # EMBY - MEDIA SERVER
  emby:
    image: linuxserver/emby:latest
    container_name: emby
    hostname: emby
    networks:
      - arr-net
    mem_limit: 2g
    memswap_limit: 2g
    volumes:
      - ${DOCKER_BASE_FOLDER}/emby:/config
      - /media/steve/SteveBStor1/entertainment/home_movies:/data/home
      - ${MEDIA_DISK_LOCATION}/shows:/data/tvshows
      - ${MEDIA_DISK_LOCATION}/movies:/data/movies
      - ${MEDIA_DISK_LOCATION}/music:/data/music
      - ${DOCKER_BASE_FOLDER}/shared:/shared
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8096:8096
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${MY_TMZ}
    labels:
      - "com.containrrr.watchtower=true"

  # OMBI
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    hostname: ombi
    networks:
      - arr-net
    mem_limit: 256m
    memswap_limit: 256m
    volumes:
      - ${DOCKER_BASE_FOLDER}/ombi/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3579:3579
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${MY_TMZ}
    labels:
      - "com.containrrr.watchtower=true"

  # JELLYSEERR
  seerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: seerr
    hostname: seerr
    networks:
      - arr-net
    mem_limit: 512m
    memswap_limit: 512m
    volumes:
      - ${DOCKER_BASE_FOLDER}/seerr/config:/app/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5055:5055
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - TZ=${MY_TMZ}
    labels:
      - "com.containrrr.watchtower=true"

networks:
  arr-net:
    driver: bridge
